import { useState, type ImgHTMLAttributes } from "react";
import { publicUrl } from "@/lib/publicUrl";

/** Widths generated by scripts/optimize-images.mjs into public/images/opt/. */
const OPT_WIDTHS = [480, 960, 1600] as const;

export interface ImgProps
  extends Omit<
    ImgHTMLAttributes<HTMLImageElement>,
    "alt" | "src" | "loading" | "width" | "height" | "decoding"
  > {
  /** Path to the original file in public/images/, e.g. "graduate.jpg" or "/images/graduate.jpg". */
  src: string;
  /** Required — TypeScript enforces this, there is no default. */
  alt: string;
  /** Intrinsic pixel width, used both to prevent CLS and to cap which opt/ widths are requested. */
  width: number;
  height: number;
  /** Hero-image mode: fetchpriority="high" + loading="eager" instead of lazy. */
  priority?: boolean;
  sizes?: string;
}

/** Logical (pre-base) "images/..." path — `publicUrl` applies the real base at the point of use. */
function normalizeSrc(src: string): string {
  if (src.startsWith("/")) return src.slice(1);
  return `images/${src}`;
}

function stemOf(src: string): string {
  const basename = normalizeSrc(src).replace(/^images\//, "");
  const dot = basename.lastIndexOf(".");
  return dot === -1 ? basename : basename.slice(0, dot);
}

/**
 * React 18's react-dom has no special-case mapping for `fetchPriority` (that
 * was added in React 19) — passing the camelCase prop just warns and sets a
 * useless "fetchPriority" DOM attribute. Passing the raw lowercase attribute
 * name through an untyped spread sets the real `fetchpriority` HTML
 * attribute the browser reads, with no warning.
 */
function fetchPriorityAttr(priority: boolean): Record<string, string> {
  return priority ? { fetchpriority: "high" } : {};
}

/**
 * Renders a `<picture>` with a webp `srcSet` (480/960/1600 from
 * public/images/opt/) plus a fallback `<img>` to the original file, per
 * docs/BUILD-PROMPT.md §4/plan Task 5.
 *
 * Handles the zero-variant case gracefully (some source images are narrower
 * than 480px, so the optimizer skipped generating any opt/ variants for
 * them — see .superpowers/sdd/PLAN/progress.md): candidate widths wider than
 * the image's own intrinsic `width` are never requested (mirroring the
 * optimizer's own "never upscale past the original" rule), and if a webp
 * variant 404s anyway, `onError` drops the `<source>` entirely so the
 * `<img>` falls back to the plain original — never a broken image.
 */
export default function Img({
  src,
  alt,
  width,
  height,
  priority = false,
  sizes = "100vw",
  className,
  ...rest
}: ImgProps) {
  const [webpFailed, setWebpFailed] = useState(false);

  const original = publicUrl(normalizeSrc(src));
  const stem = stemOf(src);
  const candidateWidths = OPT_WIDTHS.filter((optWidth) => optWidth <= width);
  const showWebpSource = !webpFailed && candidateWidths.length > 0;

  const srcSet = candidateWidths
    .map((optWidth) => `${publicUrl(`images/opt/${stem}-${optWidth}.webp`)} ${optWidth}w`)
    .join(", ");

  return (
    <picture>
      {showWebpSource && <source type="image/webp" srcSet={srcSet} sizes={sizes} />}
      <img
        src={original}
        alt={alt}
        width={width}
        height={height}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        className={className}
        onError={showWebpSource ? () => setWebpFailed(true) : undefined}
        {...fetchPriorityAttr(priority)}
        {...rest}
      />
    </picture>
  );
}
